version: '3.8'

services:
  code-server:
    image: localhost:5000/code-server:latest
    container_name: code-server
    ports:
      - "2222:2222"
    volumes:
      - code-server:/users-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    command: ["/bin/bash","-c","/usr/local/bin/init-users.sh"]

volumes:
  code-server:
    external: true